### PR TITLE
Added configurable browser title #349

### LINKED ISSUE #349: title for index.haml
Hello,

Is it possible to add the hostname of raspberry in HTML title ?

I try :
%title Screnly OSE server.hostname

But doesn't works

### PR DESCRIPTION
**Pull request by pearson-lucas-dev**
This should close #349 if accepted

[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/356)

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks for the work here. It might take some time for us to review this at the moment.

**Comment by pearson-lucas-dev** [comment]
@vpetersson No problem, if it gets stale and starts to have conflicts please let me know and I will update the PR.

**Comment by pearson-lucas-dev** [comment]
@vpetersson Just wondering how much longer you thought it might be look get this changes in there?

**Comment by vpetersson** [comment]
@pearson-lucas-dev I'll try to carve out some resources in the next Screenly Pro sprint for this.

**Comment by pearson-lucas-dev** [comment]
@vpetersson Should I bother resolving the conflicts for this branch or is it pretty low on the priority list?

**Comment by vpetersson** [comment]
@pearson-lucas-dev Looked over the diff real quick. Wouldn't it make more sense to use the hostname of the box rather than something defined in `screenly.conf`?

**Comment by pearson-lucas-dev** [comment]
@vpetersson I was under the impression that configurable meant that it wasn't something that was already defined such as a hostname but it doesn't really matter to me either way I was just trying to help out with a project I thought was cool.  Getting a little open source and python action in the process.

**Comment by vpetersson** [comment]
@pearson-lucas-dev Yeah this wouldn't be done in `screenly.conf` if so but rather natively by calling `socket.gethostname()`. That said, I'm still not 100% sure which way is better.

**Pull request closed without merging**
