### PR TITLE
Use custom text handler in bottle templates. Decode strings as unicode

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/347)

### CODE REVIEW

**Comment by over64** [comment]
according to http://stackoverflow.com/questions/3333550/how-to-deal-with-unicode-in-mako

**Comment by femdom** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pwrjbkU1dU0Z17wK4:-K7pwrjbkU1dU0Z17wK5:1895404228) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/server.py#L98)):*
Consider adding a comma in the end after this line.

---

*[utils.py, line 104 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7puPC8UCyvg4lpRZaw:-K7puPC8UCyvg4lpRZax:307330646) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L104)):*
We don't use builtins as variable names. I used to use it in the past, but now I believe that naming a variable with a name other than built-in is worth of time spent.  

---

*[utils.py, line 105 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pvYu95qdBD42UK0X3:-K7pvYu95qdBD42UK0X4:981235608) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L105)):*
Imagine that you get str=u"Строка"

    In [16]: unicode(s.decode(u"Строка"))
    ---------------------------------------------------------------------------
    UnicodeEncodeError                        Traceback (most recent call last)
    <ipython-input-16-b2ab93379b58> in <module>()
    ----> 1 unicode(s.decode(u"Строка"))

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

---

*[utils.py, line 106 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pwgs07cmoabFcIaB-:-K7pwgs07cmoabFcIaB0:2083438697) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L106)):*
Not necessary to wrap value with unicode after str.decode

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by femdom** [comment]
I've posted comments but, in general, I'm not agree with this solution. I need to investigate a bug report first.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-:-K7px52oKaM_EQuIzCqM:-418352950)*

**Comment by femdom** [comment]
@GreatFruitOmsk, can you, please, provide a bug report for this diff?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-:-K7py6zmmco2MAfI5YpW:1461177436)*

**Comment by femdom** [comment]
Oh. Sorry. This were for @over64.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-:-K7pzda9_6DN2QNGeeBR:1320979951)*

**Comment by femdom** [comment]
*[utils.py, line 105 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pvYu95qdBD42UK0X3:-K7qC8R5hh0ActcBsJ5v:2019155178) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L105)):*
Omg...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by femdom** [comment]
*[utils.py, line 105 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pvYu95qdBD42UK0X3:-K7qCKacsWl7RVUP9ZeS:761289822) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L105)):*
Sorry. Meant

    In [3]: unicode(u"Строка".decode("utf-8"))
    ---------------------------------------------------------------------------
    UnicodeEncodeError                        Traceback (most recent call last)
    <ipython-input-3-b996e4dd87e7> in <module>()
    ----> 1 unicode(u"Строка".decode("utf-8"))

    /home/renat/.virtualenvs/screenly-pro/lib64/python2.7/encodings/utf_8.pyc in decode(input, errors)
         14 
         15 def decode(input, errors='strict'):
    ---> 16     return codecs.utf_8_decode(input, errors, True)
         17 
         18 class IncrementalEncoder(codecs.IncrementalEncoder):

    UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-5: ordinal not in range(128)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by femdom** [comment]
I'm not sure that Unicode decode error should be resolved that way. Anyhow, this doesn't mean that the solution I'm thinking about it right. Maybe we should check that all values we pass to the mako template are already utf-8 decoded, without touching mako filters. 

Is it possible? Or is it worth of time we will spend on it?

@aljungberg, can you please see my comment

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-:-K7qEWLYCB6ffjeTfI1f:-957311133)*

**Comment by femdom** [comment]
*[server.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7pwrjbkU1dU0Z17wK4:-K7qEuPa4zsHJKi9CBUM:-1898753845) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/server.py#L98)):*
It's good practice - to use trailing comma when defining sequences.

Here is the stackoverflow question about it.

https://stackoverflow.com/questions/11597901/why-does-python-allow-a-trailing-comma-in-list

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by femdom** [comment]
*[utils.py, line 105 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/347#-K7qFbvkyQeBC0uYfF3r:-K7qFbvkyQeBC0uYfF3s:243508533) ([raw file](https://github.com/wireload/screenly-ose/blob/d0ad3dc4af94ac9065a410feb9d7725d7e097f8e/utils.py#L105)):*
Ah.. Forgot to mention: 

This happens because in python 2.7 

    In [8]: issubclass(unicode, basestring)
    Out[8]: True

    In [9]: issubclass(str, basestring)
    Out[9]: True

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by femdom** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/347)*

**Comment by vpetersson** [comment]
Refs #344.

**Comment by vpetersson** [comment]
@over64 This cannot be merge due to conflicts.

**Pull request merged**
