### PR TITLE
escape @ in URI for UZBL

### PR DESCRIPTION
**Pull request by over64**
https://github.com/wireload/screenly-ose/issues/515

### CODE REVIEW

**Comment by vpetersson** [comment]
Awesome. Did you end-to-end test this?

**Comment by sodabrew** [comment]
:heart:

**Comment by sodabrew** [comment]
Note that the @ sign is legal in a URL in other positions as a literal character (i.e. `http://foo:bar@example.com/legal@url`), so I would expect that this fix actually _fixes_ the behavior where UZBL was consuming the @ sign in other locations as a variable sigil. Since UZBL variables are not accessible from Screenly, there shouldn't be a down side of preventing their use.

**Comment by vpetersson** [comment]
@sodabrew That's a very good point. @over64 we should split the string at the first `@` and only parse that (if you know what i mean).

**Comment by sodabrew** [comment]
Well, I mean that the previous behavior did allow UZBL to interpret at-signs as variable sigils, but users of Screenly probably would not have known that / would not have had access to set those variables, so this change actually fixes the ability to put an at-sign into a URL for a Screenly Asset.

**Comment by over64** [comment]
@sodabrew, @vpetersson thanks. Fixed in https://github.com/wireload/screenly-ose/pull/526

**Pull request merged**
