### PR TITLE
fix black screen between image assets

### PR DESCRIPTION
**Pull request by over64**
This change is [Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/458)

### CODE REVIEW

**Comment by rsenio** [comment]
Is this now available on the regular update instead of the dev release?

**Comment by vpetersson** [comment]
No, only in the dev release for now. We need to do some more testing first.

**Comment by vpetersson** [comment]
@MydKnight This is for *images*. We can't do seamless transition between videos in Screenly OSE because of the way the playback mechanism works (i.e. it's using separate threads of `omxplayer` for each video). We do however have seamless playback in the commercial version. For more info see [this page](https://www.screenly.io/screenly-ose-vs-pro/).

**Comment by MydKnight** [comment]
Ah, ok. So screenly isn't going to work as a replacement for the product
I've been using for a few years which seems to get around the problem by
precaching. I like the web interface, but the black screen is going to be a
poison pill for us, unfortunately.

**Comment by vpetersson** [comment]
@MydKnight we're happy to accept contributions to address the issue, but as mentioned, it's a solved problem in the commercial version.

**Comment by MydKnight** [comment]
No worries. Found another solution that I was able to successfully containerize.

**Pull request merged**
