### PR TITLE
explicitly set 'sudo: false' for migration to new travis infrastructure

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/332)

### CODE REVIEW

**Comment by vpetersson** [comment]
Why do we need to do this?

**Comment by over64** [comment]
https://docs.travis-ci.com/user/migrating-from-legacy/
from manual
````
How can I use container-based infrastructure? #

If you see This job is running on container-based infrastructure in your build log it means you are already running builds on our new container-based infrastructure.

If you don’t, to use the new infrastructure add the following line to your .travis.yml:

sudo: false
```

**Comment by vpetersson** [comment]
Right...but we're not using a container based infrastructure. Check out the [Travis file](https://github.com/wireload/screenly-ose/blob/master/.travis.yml).

**Comment by over64** [comment]
container based - it's new architecture for Travis based on Docker images. But Docker doesn't allows sudo.
Before this Travis used virtual machines which was slow and heavy. This repo was created when travis has no containers. For migration to dockerized containers(Travis team strongly recommends do it. And shows warning in UI) we need to explicitly said to travis that we are not using sudo. After this Travis will automaticaly switch our build to container-based arch. Tornado build for example https://github.com/tornadoweb/tornado/blob/master/.travis.yml

**Comment by vpetersson** [comment]
Ok, sounds reasonable.

**Pull request merged**
