### PR TITLE
try do HEAD then do GET if fails for url check 

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/335)

### CODE REVIEW

**Comment by femdom** [comment]
*[utils.py, line 92 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5Ef65q-Lp2YVhjw8aX:-K5Ef65q-Lp2YVhjw8aY:-291551553) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L92)):*
This is the same you wrote below. 
Make this docstring cleaner. 

For example: "Check whether uri is reachable"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils.py, line 19 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EgBpN_90qchrGCvJN:-K5EgBpN_90qchrGCvJO:-2091599456) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L19)):*
Name of the function is not what it does.

I believe that function validate_url should raise an exception if url is invalid. 
Otherwise it should be named: url_valid or something like this. 

I'm not 100% sure. What is your opinion?

---

*[utils.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EkPY761H454rBSt-p:-K5EkPY761H454rBSt-q:1386667955) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L98)):*
Code with too much negations hard to understand.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by over64** [comment]
*[utils.py, line 19 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EgBpN_90qchrGCvJN:-K5ZL2GwcGsUblxRiNDS:1672886706) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L19)):*
The problem that this is "by design" . This function should be named as is_http_uri and should return true or false

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by over64** [comment]
*[utils.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EkPY761H454rBSt-p:-K5ZWcLb_tOK7OHedPjG:-1587866362) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L98)):*
By design error. this function should validate not only http/https URIs  - it should validate files too (file://), and it should be named as uri_fails. There is only one problem - we already have code, which based on this wrong design(

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
*[utils.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EkPY761H454rBSt-p:-K5_WP3iIBQUcmCNMU7v:1539630220) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L98)):*
try:
    if not validate_url(url):
        return False

    if requests.head(url, allow_redirects=True, timeout=10, verify=settings['verify_ssl']).status_code in (200, 405):
        return False
   
    if requests.get(url, allow_redirects=True, timeout=10, verify=settings['verify_ssl']).status_code == 200:
        return False
except (requests.ConnectionError, requests.exceptions.Timeout):
    pass

return True

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[utils.py, line 19 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EgBpN_90qchrGCvJN:-K5_Vdr1TRkTLrcyr8XZ:95681942) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L19)):*
Cool name. Is it possible to rename it?

---

*[utils.py, line 98 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-K5EkPY761H454rBSt-p:-K5_XyKDpcujosNxaf7u:794207400) ([raw file](https://github.com/wireload/screenly-ose/blob/044282d173a3a63213b55683fb80984f9b6c7c6e/utils.py#L98)):*
Sorry. Here is right code

    try:
        if not validate_url(url):
            return False

        if requests.head(url, allow_redirects=True, timeout=10, verify=settings['verify_ssl']).status_code in (200, 405):
            return False
   
        if requests.get(url, allow_redirects=True, timeout=10, verify=settings['verify_ssl']).status_code == 200:
            return False
    except (requests.ConnectionError, requests.exceptions.Timeout):
        pass

    return True

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[utils.py, line 96 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwemfOeAGr8beZhvzQ:-KDwemfOeAGr8beZhvzR:-1034006862) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L96)):*
1. What if we will accept all responses in the range of [200. 299]?
2. Just noticed that 405 response is "Method not allowed." Let us not accept this error code, because we anyhow do one more GET below.

---

*[utils.py, line 99 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwh_FuP8nmYYrcEFeC:-KDwh_FuP8nmYYrcEFeD:218676795) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L99)):*
I think - we should accept any response in the range of [200. 299]

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by vpetersson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[utils.py, line 96 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwemfOeAGr8beZhvzQ:-KDwsK7YX5rY_WW7UP4t:-971457105) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L96)):*
Yeah, i think you're right. 200-299 would be better.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by vpetersson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[utils.py, line 99 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwh_FuP8nmYYrcEFeC:-KFjNCehrfS_8AyoVwj8:-1530771663) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L99)):*
Agreed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by over64** [comment]
*[utils.py, line 99 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwh_FuP8nmYYrcEFeC:-KGFOboMHC0fK6h3Rnz8:-497468049) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L99)):*
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by over64** [comment]
*[utils.py, line 96 \[r2\]](https://reviewable.io:443/reviews/wireload/screenly-ose/335#-KDwemfOeAGr8beZhvzQ:-KGFOdU8zbsYlSwcfxAG:-497468049) ([raw file](https://github.com/wireload/screenly-ose/blob/7d9197c2bd68cba9f8010e9ce00d01160ba17712/utils.py#L96)):*
Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Comment by femdom** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wireload/screenly-ose/335)*

**Pull request merged**
