### PR TITLE
make asset type immutable via edit

### PR DESCRIPTION
**Pull request by over64**
image

---
This change is [Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/466)

### CODE REVIEW

**Comment by vpetersson** [comment]
@over64 please refer to the ticket/issue number you're fixing os that we have a link (such as `Closes #XXX`).

**Comment by vpetersson** [comment]
Looks god to me other than that.

**Comment by over64** [comment]
@vpetersson, ok

**Comment by vpetersson** [comment]
Closes #416.

**Pull request merged**
