### PR TITLE
Auth changes

### PR DESCRIPTION
**Pull request by axel-b**
For your information: the changes I made to enable (basic and) ldap authentication.

Note: to use this, you need:
     sudo apt-get install python-paste
     sudo apt-get install python-ldap

Note that I run this via stunnel, set-up via the ~/screenly/misc/enable_ssl.sh script provided with screenly.
Note that when you enable stunnel using that script, you have to change the firewall rules to open port 443, by issuing: sudo ufw allow 443/tcp
Probably this should be fixed in the ~/screenly/misc/enable_ssl.sh script.

(Edited to include 'sudo apt-get install python-ldap')

[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/224)

### CODE REVIEW

**Comment by mrneilsy** [comment]
LDAP auth would be a very big plus for any organisation with multiple screenly devices and lot's of staff. I'm currently testing the jpsingleton basic auth fork https://github.com/jpsingleton/screenly-ose but proper LDAP would be heaps better.

**Comment by axel-b** [comment]
> On 30 Jun 2015, at 01:44, mrneilsy <notifications@github.com> wrote:
> 
> https://github.com/jpsingleton/screenly-ose <https://github.com/jpsingleton/screenly-ose>
my (by now old) LDAP stuff is among the branches in my screenly  fork at   https://github.com/axel-b/screenly-ose <https://github.com/axel-b/screenly-ose>  and at  https://github.com/wireload/screenly-ose/pull/224 <https://github.com/wireload/screenly-ose/pull/224>  where you will also find the comments of the wireload reviewer. In my patch I also integrated some other stuff like a different logging package to get logging with user names.

My branch effectively worked; main weak point (IMHO) was on how to specify the configuration.

I did not further pursue the pull request because a) screenly moved on since my changes, and more importantly   b)  I changed jobs and I’m no longer involved with running screenly.

Axel.

**Comment by mrneilsy** [comment]
If LDAP auth is progressing I'll be a very happy chappy.

**Comment by vpetersson** [comment]
@mrneilsy we're going down the route of #495 right now. it's a less complex change that wouldn't require a huge refactoring. 

LDAP is a bit more complex (by the nature of the protocol).

**Pull request closed without merging**
