### PR TITLE
new logo

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/336)

### CODE REVIEW

**Comment by vpetersson** [comment]
Can you please post screenshots, @over64?

**Comment by Kentzo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[static/css/screenly.css, line 19 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/336#-K5EM0X5zXQJwUvfq04E:-K5EM0X5zXQJwUvfq04F:-1058466595) ([raw file](https://github.com/wireload/screenly-ose/blob/da387090d3d893c62925011f1f1c41aaffce3704/static/css/screenly.css#L19)):*
Why black -> #000 ?

---

*[views/splash_page.haml, line 17 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/336#-K5EM8PutqkBfVNomQ4G:-K5EM8PvncfSML3xHTBg:2139438095) ([raw file](https://github.com/wireload/screenly-ose/blob/da387090d3d893c62925011f1f1c41aaffce3704/views/splash_page.haml#L17)):*
Single quote or double quote after all?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/336)*

**Comment by over64** [comment]
image
image
image
image

**Comment by over64** [comment]
*[views/splash_page.haml, line 17 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/336#-K5EM8PutqkBfVNomQ4G:-K5ESPQoadb4ufihlQtT:1102398147) ([raw file](https://github.com/wireload/screenly-ose/blob/da387090d3d893c62925011f1f1c41aaffce3704/views/splash_page.haml#L17)):*
double quote for html tag attributes, single for strings in JS/coffee

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/336)*

**Comment by over64** [comment]
*[static/css/screenly.css, line 19 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/336#-K5EM0X5zXQJwUvfq04E:-K5EUIKgeRaLWFhAIfB-:-1261847460) ([raw file](https://github.com/wireload/screenly-ose/blob/da387090d3d893c62925011f1f1c41aaffce3704/static/css/screenly.css#L19)):*
this is auto generated file. New version of sass compiler uses hex encoding for colors. And when I genereated screenly.css from SASS I forgot to remove this diff. Fixed this

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/336)*

**Pull request merged**
