### PR TITLE
Update for RPI 2

### PR DESCRIPTION
**Pull request by ghholm**

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks! 
Looks good in general, but my one concern is backward compatibility. What happens if the user tries to run this on an older Raspbian installation. Perhaps we should do both approaches simultaneously. 

Sure, it won't look as good, and it will make more of a mess on the filesystem. However, unless we can detect this somehow, I don't know how we can prevent that.

**Comment by ghholm** [comment]
Maybe some conditional check if i.e. `~/.config/openbox/lxde-pi-rc.xml` exists and react to that. Or if this new `-<username>-` to each `lxde` file/path is related to an specific version of Raspbian, then have some kind of version check if the Raspbian?

**Comment by vpetersson** [comment]
Take a look at this: 
https://github.com/wireload/screenly-ose/commit/0b28da001b5dc22aa54516d2ef4c2aab997b172b

It's pretty hackish, but at least it's pretty DRY.

**Comment by ghholm** [comment]
That might work, only able to test it on PI 2.

Not sure what is wrong but my viewer.py keep restarting when I added the rasp_arch array code.

I edited the file directly from Windows through Putty SSH. Could it be some character encoding that messes up my code and breaks it?

**Comment by vpetersson** [comment]
@ghholm Try this branch:
https://github.com/wireload/screenly-ose/tree/ghholm-master

Just check it out directly on the Pi.

**Comment by pelicanmedia** [comment]
I just tried on a Pi 2
```
curl -sL https://github.com/wireload/screenly-ose/blob/ghholm-master/misc/install.sh | bash
```
But keep getting 
```
pi@raspberrypi ~ $ curl -sL https://github.com/wireload/screenly-ose/blob/ghholm-master/misc/install.sh | bash
bash: line 4: syntax error near unexpected token `newline'
bash: line 4: `<!DOCTYPE html>'
```

I'm more than likely doing something wrong

**Comment by vpetersson** [comment]
@pelicanmedia You must use:

    $ curl -sL  https://raw.githubusercontent.com/wireload/screenly-ose/ghholm-master/misc/install.sh | bash

**Comment by pelicanmedia** [comment]
Knew it would be something I was doing wrong!

I get the following error at the end:
```
pi@raspberrypi ~ $ curl -sL  https://raw.githubusercontent.com/wireload/screenly-ose/ghholm-master/misc/install.sh | bash
Installing Screenly OSE
Updating system package database...
Upgrading the system...
(This might take a while.)
Installing dependencies...
grep: /etc/init.d/mathkernel: No such file or directory
Extracting templates from packages: 100%
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.
Downloading Screenly-OSE...
remote: Counting objects: 3054, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 3054 (delta 11), reused 7 (delta 4)
Receiving objects: 100% (3054/3054), 1.12 MiB | 1.23 MiB/s, done.
Resolving deltas: 100% (1670/1670), done.
Installing more dependencies...
Adding Screenly to X auto start...
Increasing swap space to 500MB...
Adding Screenly's config-file
Enabling Watchdog...
[ ok ] Stopping watchdog keepalive daemon....
[ ok ] Starting watchdog daemon....
Adding Screenly to autostart (via Supervisord)
Making modifications to X...
ln: failed to create symbolic link `~/.config/openbox/lxde-pi-rc.xml': No such file or directory
Quiet the boot process...
Assuming no errors were encountered, go ahead and restart your computer.
pi@raspberrypi ~ $
```

**Comment by vpetersson** [comment]
Ok, looks like the hack didn't work then. I will have to test it out myself more carefully. 

Will be back in Europe soon and have access to the equipment and can start playing with it then.

**Comment by ghholm** [comment]
@vpetersson I updated some of the code since there were some minor errors in it: https://github.com/ghholm/screenly-ose/commit/85900283241008970db30dabdfa53a4fedda6fac

Tested it on a fresh Raspbian install and it worked perfectly for me yesterday.

**Comment by vpetersson** [comment]
@ghholm Looked at your code real quick, but it's hard to determine what exact change you made (since you didn't pull them in from the upstream branch). 

I will however take a closer look in the next few days.

**Comment by ghholm** [comment]
@pelicanmedia Incase you're eager and impatient as me, you could login to SSH and run installer from my fork (*I recommend a fresh install of Raspbian before you go on*):

    curl -sL https://raw.githubusercontent.com/ghholm/screenly-ose/master/misc/install.sh | bash

Then when install is complete, replace the `viewer.py` within your screenly folder by running these commands:

    rm viewer.py
    wget https://raw.githubusercontent.com/ghholm/screenly-ose/master/viewer.py
    chmod a+x viewer.py
    sudo reboot

**Pull request merged**
