### PR TITLE
Refs #229. Keeping order when activating/deactivating assets.

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/319)

### CODE REVIEW

**Comment by aljungberg** [comment]
Looks fine but requires both back-end (API) and front-end tests (Selenium). Do we have frameworks in place for this in this project yet?


---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[server.py, line 264 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K0GQX0prq7Uj0-zfjw8)** ([raw file](https://github.com/wireload/screenly-ose/blob/42112bc306fd22e580a7d00a2670d0a504dc0fd4/server.py#L264)):</sup>
This can be moved down to where you need it.


---

<sup>**[server.py, line 269 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K0GQZtBwCfLrHVlrQ45)** ([raw file](https://github.com/wireload/screenly-ose/blob/42112bc306fd22e580a7d00a2670d0a504dc0fd4/server.py#L269)):</sup>
Could just be like this:

    # Set the play order to a high value for all inactive assets.
    for asset in assets:
        if not asset['id'] in ids:
            assets_helper.update(db_conn, asset['asset_id'], {'asset_id': asset_id, 'play_order': len(ids)})

To me it's more clear. And although it doesn't really matter in this case it uses less memory since you don't create a second `last` list.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)

**Comment by over64** [comment]
We have not tests for UI. Especially tests with Selenium web driver) I will make server side test for this feature in current sprint


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)

**Comment by over64** [comment]
<sup>**[server.py, line 269 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K0GQZtBwCfLrHVlrQ45)** ([raw file](https://github.com/wireload/screenly-ose/blob/42112bc306fd22e580a7d00a2670d0a504dc0fd4/server.py#L269)):</sup>
Fixed this. It's more human readable, yes)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)

**Comment by aljungberg** [comment]
Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[assets_helper.py, line 123 \[r3\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K1sS5wS_f88Pb0aUhEP)** ([raw file](https://github.com/wireload/screenly-ose/blob/834a6b8b5ae67b7574c76dc4a4721bfae6c5ef8f/assets_helper.py#L123)):</sup>
Since this actually writes to the database it should have a verb name like `save_ordering`.


---

<sup>**[tests/server_test.py, line 198 \[r3\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K1sT2eYkyXZRyxb4VUu)** ([raw file](https://github.com/wireload/screenly-ose/blob/834a6b8b5ae67b7574c76dc4a4721bfae6c5ef8f/tests/server_test.py#L198)):</sup>
Wouldn't it make a better test if you swapped them so they're not in the natural ordering? `for_order = [asset_y, asset_x]`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)

**Comment by over64** [comment]
_[tests/server_test.py, line 198 \[r3\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K1sT2eYkyXZRyxb4VUu:-K3jzLKSpDWgqRzwGaLS:-1159612715) ([raw file](https://github.com/wireload/screenly-ose/blob/834a6b8b5ae67b7574c76dc4a4721bfae6c5ef8f/tests/server_test.py#L198)):_
test improved

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)_

**Comment by over64** [comment]
_[assets_helper.py, line 123 \[r3\]](https://reviewable.io:443/reviews/wireload/screenly-ose/319#-K1sS5wS_f88Pb0aUhEP:-K3jzPTrM8STbMFUI7lN:883545377) ([raw file](https://github.com/wireload/screenly-ose/blob/834a6b8b5ae67b7574c76dc4a4721bfae6c5ef8f/assets_helper.py#L123)):_
renamed))

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/319)_

**Comment by vpetersson** [comment]
@over64 Can you pull in the changes upstream so that we can merge this one?

**Comment by over64** [comment]
rebased)

**Pull request merged**
