### PR TITLE
escape only first @ in URI for UZBL

### PR DESCRIPTION
**Pull request by over64**

### CODE REVIEW

**Comment by over64** [comment]
https://github.com/wireload/screenly-ose/pull/525

**Comment by sodabrew** [comment]
:-1: this is bad. It will work for the `username:password@example.com` case but cause confusion in this case:
`http://example.com/weird/@strange/@url`
becomes:
`http://example.com/weird/\@strange/@url`

**Comment by vpetersson** [comment]
@sodabrew yes, you raise a valid point. I've re-opened #515.

**Comment by vpetersson** [comment]
Actually, upon further research, @over64's fix is indeed correct. `@` is a [reserved character](https://stackoverflow.com/questions/1856785/characters-allowed-in-a-url). As such, it is not a legal character in the URL.

@over64 can you redo this PR so that I can accept it again?

**Comment by sodabrew** [comment]
It's not reserved, it's legal in a URL https://tools.ietf.org/html/rfc3986

It has special meaning to the left of the hostname, but no special meaning to the right of the hostname.

For example, this is a legal link: https://www.wikipedia.org/wiki/@

**Comment by vpetersson** [comment]
Interesting. In section 2.2.  (Reserved Characters),  it says `reserved = gen-delims / sub-delims`, and then goes on to define `gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"`. That said, in typical RFC fashion, reserved character are may or may not be reserved. :)

In any case, yes, you're right. It's obviously used in some edge cases. 

We're not using any variables in UZBL, so I guess b) is a better option. 

@over64 you agree?

**Pull request merged**
