### PR TITLE
pull new sources before adding supervisor to autostart

### PR DESCRIPTION
**Pull request by over64**
[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/342)

### CODE REVIEW

**Comment by vpetersson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[misc/upgrade.sh, line 49 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/342#-K62tGcWMpZqAx-kH285:-K62tGcWMpZqAx-kH286:-1251584181) ([raw file](https://github.com/wireload/screenly-ose/blob/ec33d5494d0f47de5adf790de232297b83568082/misc/upgrade.sh#L49)):*
This won't work. Why don't you go for the solution that we discussed in the ticket (i.e. passing on the config file and/or creating the symlink).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/342)*

**Comment by over64** [comment]
*[misc/upgrade.sh, line 49 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/342#-K62tGcWMpZqAx-kH285:-K62u7OvnNrllBLbnim2:1421688771) ([raw file](https://github.com/wireload/screenly-ose/blob/ec33d5494d0f47de5adf790de232297b83568082/misc/upgrade.sh#L49)):*
https://github.com/GreatFruitOmsk/screenly-ose/blob/feature/new-supervisor2/misc/supervisor#L44
init script will try to find config in /etc/supervisor/supervisor.conf. Maybe supervisorctl will not work. But is really need? Init script was copied from debian package. Tested this just today. The problem was that I made update-rc.d before supervisor init script was pulled from repo. Sadly( If we really need supervisorctl I can make additional symlink to /etc/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/342)*

**Comment by vpetersson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[misc/upgrade.sh, line 49 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/342#-K62tGcWMpZqAx-kH285:-K62vnTPVkyODi6NqtgR:773908429) ([raw file](https://github.com/wireload/screenly-ose/blob/ec33d5494d0f47de5adf790de232297b83568082/misc/upgrade.sh#L49)):*
Yes, we should make sure that `supervisorctl` works too. The above approach won't work because you can't start the service if it is already running. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/342)*

**Comment by over64** [comment]
*[misc/upgrade.sh, line 49 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/342#-K62tGcWMpZqAx-kH285:-K62vkQuV_wszOzxcIGl:-109870464) ([raw file](https://github.com/wireload/screenly-ose/blob/ec33d5494d0f47de5adf790de232297b83568082/misc/upgrade.sh#L49)):*
Ok ok, need some time for test it

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/342)*

**Comment by vpetersson** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/342)*

**Comment by vpetersson** [comment]
Thanks!

**Pull request merged**
