### PR TITLE
Add license file (GPL-2.0 + commercial)

### PR DESCRIPTION
**Pull request by mk-fg**
I'm not much into legal stuff, so not sure if it's done right, but I've had a bit of trouble finding the license for this project, with most obvious location (LICENSE or COPYING file in the project dir) being sadly absent.

Currently it seem to be only mentioned in the docs on [screenlyapp.com](https://www.screenlyapp.com/ose/#licensing) and vewer.py / server.py headers.

[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/330)

### CODE REVIEW

**Comment by vpetersson** [comment]
Thanks!

**Comment by mk-fg** [comment]
Fixed

**Comment by mk-fg** [comment]
"GPLv2 public license" also seemed very redundant, so changed to "GPLv2 text follows" keeping acronym as it was used above.

**Comment by mk-fg** [comment]
Thanks!

**Pull request merged**
