### PR TITLE
Re #123. Solves uploads of larger assets.

### PR DESCRIPTION
**Pull request by over64**
Use werkzeug for handle multipart instead of bottle. Now progressbar works as expected.

[Review on Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/317)

### CODE REVIEW

**Comment by vpetersson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[server.py, line 111 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GHO8zhtj4MpTTYMCh)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L111)):</sup>
Maybe a bit confusing to have both `Requests` and `requests` in the same module?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by vpetersson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[server.py, line 111 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GHO8zhtj4MpTTYMCh)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L111)):</sup>
s/module/file/


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by aljungberg** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[server.py, line 117 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GKP8mahn44CA-B_tT)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L117)):</sup>
Could be simplified into the more idiomatic `data = json.loads(req.form['model']) if 'model' in req.form else req.form`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by aljungberg** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[server.py, line 111 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GHO8zhtj4MpTTYMCh)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L111)):</sup>
I can live with that.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by vpetersson** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[server.py, line 111 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GHO8zhtj4MpTTYMCh)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L111)):</sup>
Fair enough. Ignore. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by over64** [comment]
<sup>**[server.py, line 117 \[r1\]](https://reviewable.io:443/reviews/wireload/screenly-ose/317#-K0GKP8mahn44CA-B_tT)** ([raw file](https://github.com/wireload/screenly-ose/blob/b0c639c67754ead8ac63facdf56f72eb110e8be5/server.py#L117)):</sup>
magic python ternary operator)) Ok, will fix))


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Comment by aljungberg** [comment]
LGTM. Once we have browser tests we should add one for uploads.


---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wireload/screenly-ose/317)

**Pull request merged**
