### PR TITLE
Adds reload functionality of existing asset.

### PR DESCRIPTION
**Pull request by vpetersson**
TODO: Needs to be tested.

---
This change is [Reviewable](https://reviewable.io/reviews/wireload/screenly-ose/422)

### CODE REVIEW

**Comment by xdozex** [comment]
Any idea when this fix will be included in the custom image?

**Comment by vpetersson** [comment]
The easiest way is to just run the upgrade script. No need to re-flash the device.

**Comment by xdozex** [comment]
Thanks for the info, unfortunately I'm a pretty low-level user, and have no idea how to run the upgrade script :). Mind linking to some reference material if it's available?

**Comment by vpetersson** [comment]
Sure. Just SSH into the device and run:

```
bash <(curl -sL https://www.screenlyapp.com/install-ose.sh)
```

**Comment by Freyli** [comment]
Is this fixed? doesn't seem to be working for me. IE Google Slides not updating

**Comment by vpetersson** [comment]
@Freyli Yes this should have been fixed. How are you testing this?

**Comment by dvblystone** [comment]
I have two Screenly OSE devices that are running on a wireless connection. I have a single Google Slides presentation that they both are displaying. Every morning the slides are updated with current information and after saving the new presentation does not update on the Screenly. I have updated one to the most current version and the other to the advanced version. Neither one will update the content.

**Pull request merged**
